### ISSUE TITLE
Error on built ExtractHeaderTest.java

### ISSUE THREAD

**Issue by Fyne5** [jonahharris/kafka-connect-rabbitmq#4]
Dear friends,

I build this one but I meet the problem error log with ExtractHeaderTest.java, could you please let me know what can I do for this job? My enviroment: mvn 3.6.3, java-openjdk 1.8.0, centos 7

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.047 sec <<< FAILURE! - in com.github.jcustenborder.kafka.connect.rabbitmq.ExtractHeaderTest
apply()  Time elapsed: 0.047 sec  <<< ERROR!
java.lang.NoClassDefFoundError: org/apache/kafka/connect/header/Header
        at com.github.jcustenborder.kafka.connect.rabbitmq.ExtractHeaderTest.apply(ExtractHeaderTest.java:21)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.connect.header.Header
        at com.github.jcustenborder.kafka.connect.rabbitmq.ExtractHeaderTest.apply(ExtractHeaderTest.java:21)


Results :

Tests in error:
  ExtractHeaderTest.apply:21 » NoClassDefFound org/apache/kafka/connect/header/H...

Tests run: 30, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.063 s
[INFO] Finished at: 2020-05-29T17:14:07+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project kafka-connect-rabbitmq: There are test failures.
[ERROR]
[ERROR] Please refer to /root/jonahharris_kafka-connect-rabbitmq/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Thank you so much

**Comment by Fyne5** [comment]
Ok, I fixed.

##Add into pom.xml, above tag </plugins> contents:
```
 <plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-surefire-plugin</artifactId>
   <version>3.0.0-M4</version>
   <dependencies>
     <dependency>
       <groupId>org.junit.platform</groupId>
       <artifactId>junit-platform-surefire-provider</artifactId>
       <version>1.2.0</version>
     </dependency>
     <dependency>
       <groupId>org.apache.maven.surefire</groupId>
       <artifactId>surefire-api</artifactId>
       <version>3.0.0-M4</version>
     </dependency>
   </dependencies>
 </plugin>
```
And build with:
mvn package
cp -rp target/kafka-connect-target/usr/share/kafka-connect/kafka-connect-rabbitmq /opt/confluent/share/confluent-hub-components/

Done
